### ISSUE TITLE
[S1 - PBI1] Halaman Awal

### ISSUE THREAD

**Issue by mahardikamaulana** [SI-RPL-2022/SI4301-157-KotaKita#1]
### **User Story**
Halaman Awal bertujuan sebagai landing page pada saat web pertama kali dibuka/saat sebelum login berisikan informasi tentang jumlah kota, proyek, dan user yang terdaftar pada 1 tahun terakhir, perkenalan singkat tentang web, fasilitas yang ditawarkan oleh KotaKita, dan button menuju halaman Contact Us dan FAQ

### **Mock Up**
![Halaman Awal](https://user-images.githubusercontent.com/59331425/164502891-0ecc6387-280c-483c-8792-af81731c5015.png)

**Comment by tienfkusumasari** [comment]
sudah terlihat tampilan nya

**Comment by tienfkusumasari** [comment]
dipindah ke SP3
