### ISSUE TITLE
[S2 - PBI12] Halaman proyek

### ISSUE THREAD

**Issue by mahardikamaulana** [SI-RPL-2022/SI4301-157-KotaKita#10]
### **User Story**

Semua User dapat melihat Halaman Proyek untuk mendapat informasi mengenai proyek yang sedang berjalan. Semua user dapat melihat Halaman Proyek melalui halaman pilih kota > Proyek > pilih salah satu proyek dari list proyek yang tersedia

### **Mock Up**

![View Proyek (Admin)](https://user-images.githubusercontent.com/59331425/171391461-99744acc-ddcb-4265-b47b-e24e738c18c4.png)

**Comment by tienfkusumasari** [comment]
gambar header belum muncul

**Comment by tienfkusumasari** [comment]
close (SP3)
