### ISSUE TITLE
[S2 - PBI11] Membuat halaman list proyek

### ISSUE THREAD

**Issue by nauraimanda** [SI-RPL-2022/SI4301-157-KotaKita#11]
User dapat memilih proyek yang ingin dilihatnya berdasarkan list proyek yang telah ditampilkan pada halaman list proyek. lalu apabila user ingin melihat detail progres proyek maka user dapat klik button cek detail pada jenis proyek yang diinginkan.

Navigation:
Untuk seluruh role dapat melakukan login terlebih dahulu. Setelah itu akan masuk ke halaman awal yang pada kanan atas menunjukkan button Proyek. Setelah klik button Proyek maka akan menampilkan halaman pilih ingin menunjukkan halaman Proyek atau Fasilitas. Pilih button Proyek untuk menunjukkan halaman list proyek.

Note:
List proyek yang muncul itu apabila proyek tersebut belum selesai. Apabila proyek tersebut sudah selesai maka seluruh role dapat melihat pada halaman List Fasilitas.

Mockup
![image](https://user-images.githubusercontent.com/92252994/164497552-afefcc5d-bd33-418a-a683-9993dbbc4312.png)

**Comment by tienfkusumasari** [comment]
done(SP2) tambahkan issue dengan konstrain dan alur serta navigasi
