### ISSUE TITLE
[S2 - PBI13] Halaman input progress proyek

### ISSUE THREAD

**Issue by mahardikamaulana** [SI-RPL-2022/SI4301-157-KotaKita#12]
### **User Story**

Admin menginputkan progres dari proyek yang dipilih. Admin dapat melihat halaman input proyek melalui navbar proyek > pilih kota > pilih proyek > klik tombol edit proyek

### **Mock Up**

![Tambah Progress Proyek](https://user-images.githubusercontent.com/59331425/171392413-84af6c9a-dc88-42f0-aa0e-70451f12d212.png)

**Comment by tienfkusumasari** [comment]
done (SP2) tambah alur dan navigasi
