### ISSUE TITLE
[S2 - PBI10] Halaman Pilih Kota

### ISSUE THREAD

**Issue by mhmdfathh** [SI-RPL-2022/SI4301-157-KotaKita#18]
User dapat mengetahui proyek dari kota mana saja dengan adanya halaman pilih kota untuk mengetahui proyek yang dikerjakan di dalam kota tersebut

![image](https://user-images.githubusercontent.com/91667353/164505562-84d5f87d-c071-4217-8a18-c125729a4212.png)

**Comment by tienfkusumasari** [comment]
tambahkan flow, done (SP2)
