### ISSUE TITLE
[S1 - PBI2] Halaman registrasi

### ISSUE THREAD

**Issue by mahardikamaulana** [SI-RPL-2022/SI4301-157-KotaKita#2]
Membuat halaman registrasi (Dimas Yusuf Faishal)
User dapat melakukan registrasi sebelum melakukan login (memiliki akses untuk masuk kedalam website KotaKita)
![image](https://user-images.githubusercontent.com/92245983/164501780-c7a7c725-bc0a-4c12-afad-a9a63a09d324.png)

**Comment by tienfkusumasari** [comment]
close
