### ISSUE TITLE
[S2- PBI5b] Membuat Backend halaman profile

### ISSUE THREAD

**Issue by mahardikamaulana** [SI-RPL-2022/SI4301-157-KotaKita#20]
Penambahan Backend pada Halaman "Profile". Memungkinkan _Button_  yang ada pada Halaman Registrasi berfungsi seperti semestinya

**Comment by tienfkusumasari** [comment]
gambar masih statis (SP2)

**Comment by tienfkusumasari** [comment]
close (SP3)
