### ISSUE TITLE
[S2 - PBI14] Membuat halaman list fasilitas

### ISSUE THREAD

**Issue by dimasyusuf41** [SI-RPL-2022/SI4301-157-KotaKita#22]
User dapat memilih fasilitas apa saja yang tersedia di kota pilihan user.
![image](https://user-images.githubusercontent.com/92245983/164503142-a5322e53-10d5-402b-9667-591a344d3492.png)

**Comment by dimasyusuf41** [comment]
Ini adalah halaman list fasilitas yang dimana akan dimunculkan list fasilitas yang sudah diinput. Ini berhubungan dengan proyek yang dimana apabila proyek selesai maka secara otomatis maka akan muncul pada list fasilitas.

**Comment by tienfkusumasari** [comment]
done (SP2)
