### ISSUE TITLE
[S2- PBI23] Membuat Halaman Create Proyek

### ISSUE THREAD

**Issue by mahardikamaulana** [SI-RPL-2022/SI4301-157-KotaKita#24]
### **User Story**

Admin dan Super Admin dapat membuat proyek baru pada halaman Create Proyek. Terdapat form untuk melengkapi pembuatan proyek baru pada Halaman Create Proyek. Halaman Create Proyek dapat diakses dari Halaman List Proyek saat login dengan akun Admin dan Super Admin

### **Mock Up**

![Buat Proyek Baru](https://user-images.githubusercontent.com/59331425/171393799-08b6d974-d01e-4086-9f55-74f2e5b4c260.png)

**Comment by tienfkusumasari** [comment]
done (view nya di issue lain) -SP2
