### ISSUE TITLE
[S2- PBI7b] Membuat Backend Halaman FAQ

### ISSUE THREAD

**Issue by mahardikamaulana** [SI-RPL-2022/SI4301-157-KotaKita#28]
Semua role dapat melihat halaman FAQ. Halaman FAQ berisikan beberapa pertanyaan yang sering muncul pada saat mengakses website. Halaman FAQ dapat diakses dari button "Cari Tau Lebih tentang kami" pada halaman awal

**Comment by tienfkusumasari** [comment]
done (SP2) lengkapi tampilan dan alur sama navigasi- kasih keterangan kalau statis (batasan)
