### ISSUE TITLE
[S1 - PBI3] Halaman login

### ISSUE THREAD

**Issue by mahardikamaulana** [SI-RPL-2022/SI4301-157-KotaKita#3]
Membuat halaman login (Amelia Purnama Putri)

contoh ==> sebagai user yang sudah terdaftar saya dapat melakukan login dan autentifikasi (dg kata kunci) sehingga saya dapat melihat kota serta proyek2 dan progress proyek yang ada di setiap kota . 

gambar mockup

probis 

![image](https://user-images.githubusercontent.com/92241567/163975006-866fc1d5-3519-427c-aa69-b3971e3f9455.png)

**Comment by ameliapptr** [comment]
![image](https://user-images.githubusercontent.com/92241567/163960487-f4ad93bb-4c74-4ca0-9a1a-4a718bdc46f8.png)

**Comment by ameliapptr** [comment]
user melakukan login dengan memasukkan email dan kata sandi sesuai dengan data yang sudah diisikan di halaman registrasi,  untuk masuk dan dapat mengakses websitenya

**Comment by tienfkusumasari** [comment]
PBI ini baru di selesikan tam[pilan saja dan belum masuk ke databased dan logic validasi nya belum dibuat pada akhir spritn 1

**Comment by tienfkusumasari** [comment]
done (SP2)
