### ISSUE TITLE
[S2 - PBI28] Membuat Halaman Tambah Fase

### ISSUE THREAD

**Issue by mahardikamaulana** [SI-RPL-2022/SI4301-157-KotaKita#30]
### **User Story**

Admin dan Super Admin dapat menambahkan fase baru pada proyek yang sedang diakses. terdapat form yang dapat diisi untuk menambahkan detil yang diperlukan dalam penambahan fase baru. Halaman "Tambah Fase" dapat diakses dari halaman proyek 

### **Mock Up**

![Buat Fase Baru](https://user-images.githubusercontent.com/59331425/171397885-b6a0b729-802b-478f-87cb-dde7e8796f32.png)

**Comment by tienfkusumasari** [comment]
done (tambahkan alur di issue)
