### ISSUE TITLE
[S2 - PBI29] Membuat Halaman Edit Fasilitas

### ISSUE THREAD

**Issue by dimasyusuf41** [SI-RPL-2022/SI4301-157-KotaKita#31]
Admin dapat menambahkan/mengedit list fasilitas yang nantinya akan di munculkan pada UI yang akan user lihat sehingga sesuai dengan kebutuhan User.

![image](https://user-images.githubusercontent.com/92245983/169746230-f4b5d38f-b410-4b0c-addb-258fe427af38.png)

**Comment by tienfkusumasari** [comment]
baru tampilan

**Comment by tienfkusumasari** [comment]
close (SP3)
