### ISSUE TITLE
[S3 - PBI30] Membuat Halaman Input Aduan

### ISSUE THREAD

**Issue by nauraimanda** [SI-RPL-2022/SI4301-157-KotaKita#34]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/92252994/173842015-1e195ccb-a711-4dc8-a6df-8ca22180a6aa.png">

Untuk mencapai halaman input aduan, user dapat click button pada 'Pengajuan' yang berada di navbar. Setelah itu, user dapat melihat halaman input aduan. Pada halaman tersebut user dapat mengisi aduan sesuai dengan form yang tertera pada halaman tersebut

**Comment by tienfkusumasari** [comment]
done(SP3)
