### ISSUE TITLE
[S3 - PBI30] Membuat Halaman laporan proyek 

### ISSUE THREAD

**Issue by dimasyusuf41** [SI-RPL-2022/SI4301-157-KotaKita#35]
Halaman List laporan proyek ini adalah halaman untuk melihat dokumen dokumen yang sudah diupload kedalam website tersebut. Nantinya User bisa melihat langsung proyekn apa saja yang sedang dijalankan oleh pemerintah tetapi dalam bentuk dokumen. Fitur ini diharapkan dapat merealisasikan salah satu tujuan dibuat nya Kotakita yaitu transparansi proyek pemerintah.
![image](https://user-images.githubusercontent.com/92245983/173849360-3aa4d75c-587e-41aa-9690-ee9804beb2a6.png)

**Comment by tienfkusumasari** [comment]
close(SP3)
