### ISSUE TITLE
[S3 - PBI31] Membuat Halaman keterangan detail fasilitas

### ISSUE THREAD

**Issue by dimasyusuf41** [SI-RPL-2022/SI4301-157-KotaKita#36]
Halaman ini adalah halaman lanjutan dari halaman fasilitas yang dimana halaman ini berfungsi untuk melihat lebih detail terkait fasililtas yang ingin diexplore oleh user. Tujuan dari halaman ini untuk memberikan informasi secara detail terkait informasi fasilitas bahkan disini juga bisa melakukan input feedback.
![image](https://user-images.githubusercontent.com/92245983/174000704-c59b7b2b-f733-42f3-8075-2d93cd9da944.png)

**Comment by tienfkusumasari** [comment]
close (SP3)
