### ISSUE TITLE
[S3 - PBI32] Membuat Halaman Manajemen User

### ISSUE THREAD

**Issue by mhmdfathh** [SI-RPL-2022/SI4301-157-KotaKita#37]
### **User Story**

SuperAdmin dapat melihat dan mengelola User pada halaman Manajemen User. SuperAdmin dapat meningkatkan role user menjadi Admin dan Delete User. Hanya SuperAdmin yang dapat mengakses halaman Manajemen User. Halaman Manajemen User dapat diakses melalui Halaman Dashboard SuperAdmin

### **Mock Up**

![Halaman Manajemen User](https://user-images.githubusercontent.com/59331425/171395862-4d40bcdb-7334-4bd1-9eb6-9a594fb045d8.png)

**Comment by mhmdfathh** [comment]
![image](https://user-images.githubusercontent.com/91667353/173889004-35713e60-78b6-4da9-8d78-61e44aaca412.png)

Ketika ingin membuka halaman manajemen user, pertama login terlebih dahulu sebagai super admin. Setelah itu akan tersambung ke dashboard dan klik manajemen user

**Comment by tienfkusumasari** [comment]
bikin issue ga standar

**Comment by tienfkusumasari** [comment]
done code nya ...

**Comment by tienfkusumasari** [comment]
close (SP3)
