### ISSUE TITLE
[S1 - PBI5] Halaman profile

### ISSUE THREAD

**Issue by mahardikamaulana** [SI-RPL-2022/SI4301-157-KotaKita#5]
Membuat halaman profil (Naura Imanda Syaffa)

User dapat melihat profilenya setelah melakukan login apakah sudah sesuai datanya atau belum. Jika ada perubahan seperti email atau domisili maka user dapat langsung klik button edit profile. 

![image](https://user-images.githubusercontent.com/92252994/164480008-478bcbe0-b455-418b-b1f2-dc45b1040cf9.png)

**Comment by nauraimanda** [comment]
![image](https://user-images.githubusercontent.com/92252994/163960277-596c9a59-81ea-40f3-aeee-6ce1825493a0.png)

**Comment by nauraimanda** [comment]
user dapat melihat profilenya setelah berhasil melakukan login apakah informasi dirinya sudah sesuai. apabila ingin diubah maka user dapat mengedit profilenya dengan mengklik button edit profil

**Comment by tienfkusumasari** [comment]
done (SP2)
