### ISSUE TITLE
[S1 - PBI7] Halaman FAQ

### ISSUE THREAD

**Issue by mahardikamaulana** [SI-RPL-2022/SI4301-157-KotaKita#7]
Membuat halaman FAQ (Dimas Yusuf Faishal)
User dapat mengetahui informasi tambahan yang biasa ditanyakan oleh user lain.
![image](https://user-images.githubusercontent.com/92245983/164502090-655830ce-9bfc-4cda-921d-53a0d3e4eb8f.png)

**Comment by tienfkusumasari** [comment]
close (SP3)
