### ISSUE TITLE
[S1 - PBI8] Halaman contact person

### ISSUE THREAD

**Issue by mahardikamaulana** [SI-RPL-2022/SI4301-157-KotaKita#8]
### **User Story**

Semua User dapat melihat halaman kontak untuk mendapat informasi kontak terkait dan mengisi form untuk menghubungi pihak developer

### **Mock Up**

![Contact us](https://user-images.githubusercontent.com/59331425/164503241-aa0fef17-fa73-409d-aab6-5ca968a4c459.png)

**Comment by tienfkusumasari** [comment]
done (SP2)
