### ISSUE TITLE
[S2 - PBI9] Membuat halaman pilih layanan

### ISSUE THREAD

**Issue by ameliapptr** [SI-RPL-2022/SI4301-157-KotaKita#9]
User Story
sebagai user, admin, dan super admin kita dapat memilih layanan yang disediakan yaitu proyek dan fasilitas sehingga user dapat melihat proyek apa saja dan fasilitas apa saja yang ada di kota tersebut

navigasi : 
masuk dulu sebagai user/admin/super admin  -> kemudian akan masuk ke halaman home -> selanjutnya klik proyek di navbar 

alurnya  : 
login -> home ->proyek

gambar mockup
![image](https://user-images.githubusercontent.com/92241567/171577060-57b3f30b-a50d-45a0-a392-e8740107bc08.png)

**Comment by tienfkusumasari** [comment]
done (SP2) tambahkan ketarangn di iisue
